### PR TITLE
Add 'Hebrew Language Review' external workflow

### LINKED ISSUE #204: Add workflow #13157 to CFE 'Choose a workflow' dropdown menu
The Scribes research team have created a new Project Builder workflow that they would like to be added to the "Choose a Workflow" prompt for the project (see https://www.scribesofthecairogeniza.org/classify). This should be underneath the 'Phase One: Sort Fragments' link.

Workflow number: 13157

Workflow title (English): Hebrew Language Review

Workflow title (Hebrew):  סיווג שפת הכתיבה

Workflow title (Arabic): forthcoming

Tagging @shaunanoordin for your attention (whenever you have time -- I know you're currently on another project!).

Tagging Scribes project manager Emily Esten here for reference: @sheishistoric

### PR DESCRIPTION
**Pull request by shaunanoordin**
## PR Overview

Closes #204

This PR adds a new workflow to the "Choose A Workflow" menu, as requested on 204.

- The "Choose A Workflow" menu can be seen by navigating to `/classify`
- The link, titled "Hebrew Language Review", is to an external workflow on zooniverse.org.
  - It's workflow ID 13157 on production (https://www.zooniverse.org/projects/judaicadh/scribes-of-the-cairo-geniza/classify?workflow=13157)
  - There's NO equivalent workflow on staging.

Screen Shot 2021-02-12 at 14 32 22

I'm genuinely not sure how the links are supposed to be categorised (is Hebrew Language Review part of Phase One? Phase Two? Its own thing? Does it needs its own "wild card" category?), or rather _how the new link should be organised visually._

@snblickhan , please tag Becky in if the screenshot above needs revision. ☝️ 

###  Status

Ready for review, but I ain't merging nor deploying until Sam gets a chance to look at this.

### CODE REVIEW

**Comment by snblickhan** [comment]
I think for simplicity's sake ok for this to be categorized with the Phase 1 workflow (even though it technically is like _phase 1.5_...). 

The way you've set it up here seems fine to me, but I'll tag @beckyrother in case she thinks it would be more appropriate rearranged another way. Once she gives the 👍  I'd say ok to move forward. 

Only thing to note is that we don't yet have an Arabic translation for this workflow title -- will it default to appearing in English if someone is viewing the CFE Arabic translation? Otherwise happy for this to be temporarily paused until we get the Arabic translation from the team.

**Comment by snblickhan** [comment]
@beckyrother just following up on the above (placement of this new option in the Scribes workflow menu)

@shaunanoordin can you let me know whether we have a 'default' option if we don't have Arabic translation for this? e.g. if someone translates the interface but this isn't translated, will it just show up in English? Or Hebrew?

**Comment by beckyrother** [comment]
Thanks for the ping @snblickhan, apologies for the delayed response. 

This layout is a little confusing. What if we add another header in the style of 'Hebrew' and 'Arabic' titled 'Phase One' and list those top two options under that? That way they'll be less likely to be missed as people reading through this list might jump down to read the large text first.

**Comment by shaunanoordin** [comment]
@snblickhan 

> Only thing to note is that we don't yet have an Arabic translation for this workflow title -- will it default to appearing in English if someone is viewing the CFE Arabic translation? Otherwise happy for this to be temporarily paused until we get the Arabic translation from the team.

That's correct, the "default" translation for _any text_ - whenever either Hebrew or Arabic isn't available - is English.

@beckyrother Like this?

Screen Shot 2021-03-02 at 14 41 25

**Review by beckyrother — APPROVED** [review]
Perfect! Thanks Shaun!

**Comment by shaunanoordin** [comment]
👍 Awesome, thanks Becky! @snblickhan this is now just waiting for your Go signal before I merge + deploy.

**Comment by snblickhan** [comment]
I'm going to reach out to Emily and ask if she's fine for this to go live w/o Arabic, or if she'd prefer for us to wait. Watch this space!

**Comment by shaunanoordin** [comment]
This is a really old PR; I'll close it for now since it's not being actively worked on, but it's easy to resurrect and merge if we need that Hebrew Language Review WF in.

**Pull request closed without merging**
