### PR TITLE
Prepare for 2019 February/March launch

### PR DESCRIPTION
**Pull request by shaunanoordin**
## PR Overview

This PR prepares the Scribes of the Cairo Geniza project for full (public) launch.

Changes made:
- re-enabled links to Easy Arabic, Advanced Arabic, Easy Hebrew, Advanced Hebrew workflows, on the home page and the workflow selection page.
- That's about it.

Still on the TODO:
- [ ] Have a full flow check
  - [x] can users login/logout?
  - [x] can users choose a workflow, THEN change to another one?
  - [x] can users save and resume transcription work?
  - [x] can users switch between different languages?
  - [x] can users copy an SVG keyword on ALL browsers?
- [x] Check what happened to the Hebrew/Arabic Phrases workflows

### Status
This PR is on standby until @snblickhan gives the signal for either @wgranger or me to launch.

Notes:
- merge, _then_ deploy pls
- Shaun: if you can't run the code, modify package.json's engines.

### CODE REVIEW

**Comment by shaunanoordin** [comment]
## PR Update
- The Advanced Hebrew and Advanced Arabic workflows have once again been disabled
- The wording for the "Choose New Workflow?" prompt (which pops up after a user is already on a workflow, but clicks on the "Classify" nav link) has been fixed

**Comment by wgranger** [comment]
**What happened to the Hebrew/Arabic keyword workflows?** 

There are two project-builder "keyword" workflows on development (`6529`, `6600`). These workflows are currently private, but they determine what will be shown on the SVG overlay in the custom frontend (CFE).

When a user selects "Challenging Hebrew" (`6653`) or "Challenging Arabic" (`6655`) on the CFE, a GraphQl request will fetch reductions from Caesar for the corresponding keyword workflow (Hebrew: `6529` or Arabic: `6600`). Those reduction results are parsed to display the SVG overlay.

**Comment by shaunanoordin** [comment]
Merge conflict... with `package-lock.json`? Oh, it's on now.

**Comment by shaunanoordin** [comment]
OK, merge conflict has been sorted. 👍

**Comment by shaunanoordin** [comment]
This branch has been updated with the latest (final?) Hebrew and Arabic translations. This PR is ready to be merged and deployed whenever it's Go Time. (Note: the current time is currently not Go Time)

**Pull request merged**
