### PR TITLE
Address Review Notes

### LINKED ISSUE #76: Add "What's this" modal to text modifiers in the transcribe modal
https://invis.io/VAI06UDFSRH#/295137968_Transcribe-4-5-Transcribe-Info

I know, I know, modals on modals. 

While this is visible, other elements of the page should not be clickable; clicking outside of the modal should close the modal. Note the carat pointing up to the X - the modal should always be centered on that X.

Feel free to edit copy, @snblickhan.

### PR DESCRIPTION
**Pull request by wgranger**
Several issues from #72 are addressed here, but I capped the PR to three commits to keep it from getting to large. Also another wacky diff due to package-lock.json. Changes include:

- "Add Previous Marks" button functionality
- Change text for "transcribe" workflows on landing page
- Adjust CSS for CribSheet snippets
- Create `.div-shadow` class for components using `box-shadow` to share
- Update FontAwesome to version 5 (to acquire question mark style from [inVision prototype](https://projects.invisionapp.com/share/VAI06UDFSRH#/screens/295137968_Transcribe-4-5-Transcribe-Info)).
- Implement help box for TextModifiers. Closes #76

### CODE REVIEW

**Comment by simensta** [comment]
Hey @wgranger, is the Show Previous Marks button intended to toggle off all marks, including the marks for the current annotation?

**Comment by wgranger** [comment]
Ahh, good point. On consideration, I don't think it should toggle off the current annotation.

**Comment by simensta** [comment]
When changing the crib sheet script, the script options are overflowing the dialog. I don't see this on the master branch, so it may be caused by the  css updates for the crib sheet.
crib_sheet_overflow

**Comment by simensta** [comment]
I noticed some of the buttons overflow the dialog when the keyboard is closed. Maybe this is related to the css that is affecting the [crib sheet as described in my previous comment](https://github.com/zooniverse/scribes-of-the-cairo-geniza/pull/82#issuecomment-388182424)?

buttons_overflow_the_dialog

**Comment by shaunanoordin** [comment]
Merge conflict detected, attempting to resolve before code rev- ARE YOU KIDDING ME? A merge conflict on package-lock.json??? Wacky diff, go home, you're drunk.

**Comment by shaunanoordin** [comment]
Merge conflict resolve, resuming review.

**Comment by shaunanoordin** [comment]
- Code changes look good.
- Functionality looks good, but some functions trigger null-existence errors. Doesn't crash the program though, and they don't trigger on major events, so... 🤷‍♂️ 
- Minor fixes pushed into this branch for the few null-existence errors I could properly debug.
- Now addressing Andrea's comments. 👍

**Comment by shaunanoordin** [comment]
OH DANGIT! I'm going through this PR way too fast that I'm slipping on my documentation, I'm so sorry.

@simensta I meant to make a note that I managed to replicate the overflow issue you saw... on the Field Guide, but _not_ the Cribsheet or the Selected Annotation (transcription popup). I'm marking the problem as "solved" since (IIRC) the overflow for Crib Sheet and Selected Annotation was actually fixed in another PR, and that PR was recently merged into this PR as part of a merge conflict resolution. So the only thing I had to do was fix the Cribsheet in my PR update.

So anyway, TL;DR is that the overflows _should_ now be fixed for Cribsheet, SelectedAnnotation, and Field Guide, but please let me know if you notice the problem persisting. Thanks again!

**Pull request merged**
