### PR TITLE
[WIP] Arabic translations update (Aug 2018)

### LINKED ISSUE #128: Add Arabic translations
All Arabic (& Hebrew) translations available [here](https://docs.google.com/document/d/13we_9qPoZiKOKdIOaTtcYD4ZnINPFvr6AelMMNoxFwI/edit?usp=sharing).

Hebrew translations are okay for now, but if any Hebrew translation is missing from the CFE, feel free to add it from the Google doc.

### PR DESCRIPTION
**Pull request by shaunanoordin**
## PR Overview
This PR updates the Arabic translations. Closes #128 ; see that issue for the translation document.

### Status
WIP

### CODE REVIEW

**Comment by shaunanoordin** [comment]
As of 1 Aug 14:59, I think I ran out of _translated_ text? (i.e. no more new Hebrew/Arabic text to paste into the translation files.) There's still English text that _needs_ to be translated though.

**Comment by shaunanoordin** [comment]
I'm just checking in on the Arabic translations - @wgranger you've followed up with a lot of the missing text that I missed, but is there still text that we're waiting for the translators to take on?

**Comment by wgranger** [comment]
Yes, all the missing translations (as of the time of this PR) are listed [here](https://docs.google.com/document/d/1rb-PZodD5wwaNTX6fB6uzndA8fk0pB6Hgb5XjQF6J70/edit)

**Comment by shaunanoordin** [comment]
New updates!
- [Latest Hebrew Translations](https://docs.google.com/document/d/1j_C9h1vKiIeWdCNY2Oj66QNyqNUveilbbdjrcUiUgOM/edit?usp=sharing)
  - Note that some text needs to be _replaced_ with better translations
- [Latest Arabic Translations](https://docs.google.com/document/d/13we_9qPoZiKOKdIOaTtcYD4ZnINPFvr6AelMMNoxFwI/edit?usp=sharing)

Thanks to @snblickhan  for the update. These translations are considered "done" and we expect no further updates.

**Comment by wgranger** [comment]
What's the status of this PR? Can we remove the WIP? I'm not sure if other merges have covered the translations here. Looks like there are several merge conflicts.

**Comment by snblickhan** [comment]
I believe it's complete, since we had confirmation from the Penn team that Arabic translations on the CFE were done.

**Comment by shaunanoordin** [comment]
Ruh roh! This PR is no longer safe to merge, so I'm re-reviewing the changes and putting the necessary ones in another PR.

This PR is now superseded by #164

**Pull request closed without merging**
