### PR TITLE
Introduce Workflow Selection

### PR DESCRIPTION
**Pull request by wgranger**
This PR introduces workflow selection in two places: buttons on the landing page and also a dropdown menu on the project header.

### CODE REVIEW

**Comment by eatyourgreens** [comment]
If it’s any help, PFE stores your workflow choice in preferences, so that you always get the last workflow you worked on when you load a classify page.

**Comment by wgranger** [comment]
I can make these changes pretty quickly. I think the best solution for now (without devoting too much time to a new UI component this close to beta, is to load the most recent workflow choice from the preferences. 

Also, we could assume simple Hebrew is the default choice, but I worry that would lead to that workflow retiring subjects much quicker than the other workflows. I can load a random workflow on first visit if that is preferable.

**Comment by shaunanoordin** [comment]
## Update
Following IMLS meeting discussions, we've decided that we'll apply the "default workflow update/fix" in a separate PR. For now (i.e. the period leading up to Beta), we are OK to have "Easy Hebrew" as the default workflow. The preferred long-term solution is the workflow popup/prompt.

This PR will now be merged so we can properly configure the app to function on the production environment. 👍

**Comment by wgranger** [comment]
It looks like the mechanism to set your most recent workflow choice in preferences is built into the PFE frontend, so if a user selects a workflow in the CFE, it will not be updated in the preferences. 

This would require some more rigging in this project to set up the preferences update. Because of that, I might opt to devoting any dev time on this to go ahead and set up the selection prompt.

**Pull request merged**
