### PR TITLE
Set Up Character Hunt SVGs

### LINKED ISSUE #47: Setup Keyword Hunt on Frontend
Some work still needs to be done to have previous annotations rendered when retrieving info from Caesar. This is part of the data pipeline structure. Information on setting up Caesar can be found on the [How-to Zooniverse repo](https://github.com/zooniverse/how-to-zooniverse/blob/master/Caesar/Setting_up_aggregation.md).

### PR DESCRIPTION
**Pull request by wgranger**
This PR creates several components to have SVG keywords displayed. Note, there is a `resizeBoundingBox()` function in the `AggregationsPane` component to allow SVG headers to expand if they are found to be longer than the actual box.

Some of the config code will have to be adjusted a bit once we have workflow selection set up to communicate correctly with Caesar.

Closes #47

### CODE REVIEW

**Comment by shaunanoordin** [comment]
Code looks good - we're making use of the Aggregations Pane that we had from ASM, so all 👍 , but I'm having trouble compiling the code. Let me wipe my `node_modules` and try again.

**Comment by shaunanoordin** [comment]
@wgranger I can't seem to run this branch; running `rm -fr node_modiles; npm install` results in this error message:

```
> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/shaun/projects/scribes-of-the-cairo-geniza/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

> gifsicle@3.0.4 postinstall /Users/shaun/projects/scribes-of-the-cairo-geniza/node_modules/gifsicle
> node lib/install.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'clone'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
```

Who the heck is `gifsicle` and what is its goshdarn problem? `master` looks OK, so it's likely an issue with the new dependencies added - either `lodash` or `graphql-request`... or maybe counterpart going from `~` to `^`.

Gimme sometime to figure what's up

**Comment by shaunanoordin** [comment]
## PR Review - Stalled 😢 
Could not review this PR. Code looks fine, but functionality could not be confirmed as I could not successfully perform a _clean install and run_ for this branch.

### Dev Notes
OK, I have no idea what's happening here, but it doesn't seem to be the new dependencies in `package.json`? I swapped in the `package.json` from `master` (remember, master was working fine) and then ran `npm install`, but it just goes florp.

As an alternative, I went to master, ran `npm install`, switched to this branch, then ran `npm install`, and the install works fine... but then `npm start` won't compile properly. This is going to be a puzzler.

🤷‍♂️ 

### Status
Assistance required with debug/investigation:  please try deleting your `node_modules` and reinstalling, to determine if you can run this branch with a clean install.

**Comment by wgranger** [comment]
I cleared my node_modules and updates the package-lock. All compiles on my end, but give this another try. The only difference I did on this branch was that I accidentally skipped a commit when rebasing (losing important work), so I had to `git reflog` to find that commit and then cherry pick the diff , which resulted in the "recover lost patch" commit.

**Comment by shaunanoordin** [comment]
IT WORKS NOW! I just did a clean `rm -fr node_modules; npm install; npm start` and it's all good. OK, I'll continue with the review for this as soon as I can.

**Comment by shaunanoordin** [comment]
## Update
Merge conflict resolved by merging master into this PR.

**Comment by wgranger** [comment]
This should be good to go. Transcriptions are blocked atop SVG items (aggregation boxes and helper messages). I also added some logic to only retrieve aggregations for particular workflows and hide the show/hide keyword boxes button when no keywords are present.

**Comment by shaunanoordin** [comment]
## PR Review (Update)
Noice! The latest changes addresses the main blocking issues from the previous PR review. Namely, now, when the user is in Annotation mode, clicking on a Keyword Hint block no longer drops an Annotation start/end marker. Nice one, @wgranger , and a special 👍 for the UX improvement where the Show/Hide Keyword Hints button is gone if there are no Keyword Hints to hide/show.

### Status
LGTM, let's get this merged.

**Pull request merged**
